# Generated by Django 4.0.5 on 2022-06-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSelector',
            fields=[
                ('PersonId', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=128)),
                ('LastName', models.CharField(blank=True, max_length=128)),
                ('ActiveFlag', models.BooleanField(default=True)),
                ('DateSelected', models.DateTimeField(blank=True)),
            ],
        ),
    ]
