# Generated by Django 4.0.5 on 2022-06-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_selector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personselector',
            options={'managed': False},
        ),
    ]
