# Generated by Django 4.0.5 on 2022-06-20 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_selector', '0002_alter_personselector_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personselector',
            table='person_selector',
        ),
    ]
